# Generated by Django 4.1.7 on 2023-04-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_restraunt_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='restaurant_pics'),
        ),
    ]
